FROM node:18.14.2

LABEL version="1.0"
LABEL description="Backend Docker Image kagwave Web - Node"
LABEL maintainer = ["contact@kagwave.com"]

WORKDIR /server/src/services/api

COPY package*.json .
RUN ls
RUN npm install --silent

COPY . .

EXPOSE 8240

CMD ["npm", "start"];